CREATE VIEW v_CleanSales AS 
 /*PASO 1: REALIZAR LA LIMPIEZA PRIMARIA HACIENDO USO DE UNA EXPRESION COMUN PARA LA TABLA*/
 WITH CleanedData AS (
 	SELECT 
	 InvoiceNo,
	 StockCode,

	 /*PRIMERO CAPITALIZA LA PRIMERA LETRA Y EN CONJUNTO QUITO LOS ESPACIOS EN BLANCO INNECESARIOS*/
	 INITCAP(TRIM(Description)) AS Description,
	 Quantity,
	 InvoiceDate,
	 UnitPrice,

	 /*CREAR LA COLUMNA TOTAL SALE*/
	 (Quantity * UnitPrice) AS TotalSale,

	 /*CONVERTIR CUSTOMERID EN UN NUMERO ENTERO LIMPIO*/
	 CAST (CustomerID AS INT) AS CustomerID,

	 /*LIMPIO ESPACIOS Y ESTANDARIZO EL PAIS*/
	 INITCAP(TRIM(Country)) AS Country

	FROM Retail_Raw
	WHERE 
		/*ME ASEGURO DE QUE NO SEAN CANCELACIONES FILTRANDO NUMERO DE FACTURA QUE NO INICIEN CON "C" Y VALORES NEGATIVOS EN CANTIDAD*/
		Quantity > 0
		AND UPPER(InvoiceNo) NOT LIKE 'C%'

		/*AHORA FILTRAR LOS CLIENTES ANONIMOS ES DECIR CON VALOR NULL*/
		AND CustomerID IS NOT NULL 

		/*FILTRAR ARTICULOS CON PRECIO UNITARIO NO NEGATIVO*/
		AND UnitPrice > 0

		/*FILTRAR LOS CODIGOS DE PRODUCTO QUE NO PARECEN REALES ES DECIR NO TIENEN AL MENOS 5 DIGITOS*/
		AND LENGTH(TRIM(StockCode)) > 4 

		/*FILTRAR DESCRIPCIONES Y PAIS YA QUE PODEMOS TENER VALORES VACIOS O CON ESPACIO*/
		AND TRIM(Description) IS NOT NULL AND TRIM(Description) != ''
		AND TRIM(Country) IS NOT NULL AND TRIM(Country) != ''
	),

/*AHORA ME ASEGURARE DE QUE NO HAY DUPLICADOS EXCATOS HACIENDO USO DE OTRA CTE*/
RankedData AS (
	SELECT
		*, 
		ROW_NUMBER() OVER(
				PARTITION BY 
					InvoiceNo,
					StockCode,
					Quantity,
					InvoiceDate,
					CustomerID
				ORDER BY 
					InvoiceDate
		) AS rn 
		FROM 
			CleanedData
)


SELECT 
	InvoiceNo,
	StockCode,
	Description,
	Quantity,
	InvoiceDate,
	UnitPrice,
	TotalSale,
	CustomerID,
	Country
FROM 
	RankedData
WHERE 
	rn = 1;
